/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20VotesSol from "./ERC20Votes.sol";
export type { erc20VotesSol };
import type * as myErc20Sol from "./MyERC20.sol";
export type { myErc20Sol };
export type { MyERC721 } from "./MyERC721";
export type { TokenSale } from "./TokenSale";
