/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  NotQuiteRandom,
  NotQuiteRandomInterface,
} from "../NotQuiteRandom";

const _abi = [
  {
    inputs: [],
    name: "getRandomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "notQuiteRandomNumber",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tossCoin",
    outputs: [
      {
        internalType: "bool",
        name: "heads",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061010b806100206000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063b41e8cad146037578063dbdff2c1146052575b600080fd5b603d6065565b60405190151581526020015b60405180910390f35b6058607d565b6040519081526020016049565b60006002606f607d565b60779190608e565b15919050565b6000608860014360af565b40919050565b60008260aa57634e487b7160e01b600052601260045260246000fd5b500690565b8181038181111560cf57634e487b7160e01b600052601160045260246000fd5b9291505056fea26469706673582212200fa9fa70cb17a2b0ea01edab797ddb68af7f465988ddd2d313a05613304115b264736f6c63430008130033";

type NotQuiteRandomConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NotQuiteRandomConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NotQuiteRandom__factory extends ContractFactory {
  constructor(...args: NotQuiteRandomConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      NotQuiteRandom & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): NotQuiteRandom__factory {
    return super.connect(runner) as NotQuiteRandom__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NotQuiteRandomInterface {
    return new Interface(_abi) as NotQuiteRandomInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NotQuiteRandom {
    return new Contract(address, _abi, runner) as unknown as NotQuiteRandom;
  }
}
