/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as overflowSol from "./Overflow.sol";
export type { overflowSol };
export type { Gas } from "./Gas";
export * as factories from "./factories";
export { Gas__factory } from "./factories/Gas__factory";
export type { OverflowTest } from "./Overflow.sol/OverflowTest";
export { OverflowTest__factory } from "./factories/Overflow.sol/OverflowTest__factory";
